name: matrix
on: push

jobs:
  Node-versions:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [6, 7, 8]
        include:
          - os: macos-latest
            node_version: 8
            macos_os: "true"
        exclude:
          - os: windows-latest
            node_version: 6
          - os: ubuntu-latest
            node_version: 8
      
    runs-on: ${{ matrix.os }}
    env:
      MACOS: ${{ matrix.macos_os }}
    steps:
      - name: Node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: After Setup-node node version
        run: | 
          node -v
          echo $MACOS

    