name: matrix
on: push

jobs:
  Node-versions:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node_version: [6, 8, 10]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: After Setup-node node version
        run: node -v
          

    