name: matrix
on: push

jobs:
  Node-versions:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node_version: [6, 8, 10]

        include:
          - os: ubuntu-latest
            node_version: 8
            is_ubuntu-8: "true"
        exclude:
          - os: ubuntu-latest
            node_version: 6
          - os: macos-latest
            node_version: 8

        
    runs-on: ${{ matrix.os }}
    env:
      IS_UBUNTU_8: ${{ MATRIX.IS_UBUNTU_8 }}
    steps:
      - name: Node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: After Setup-node node version
        run: |
          node -v
          echo $IS_UBUNTU_8

    