name: matrix
on: push

jobs:
  Node-versions:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [6, 7, 8]
        exclude:
          - os: ubuntu-latest
            node_version: 7
          - os: macos-latest
            node_version: 6

        include:
          - os: ubuntu-latest
            node_version: 7
            is_ubuntu-8: "true"
    runs-on: ${{ matrix.os }}
    env:
      IS_UBUNTU_8: ${{ matrix.is_ubuntu-8 }}
    steps:
      - name: Node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: After Setup-node node version
        run: |
          node -v
          echo $IS_UBUNTU_8

    